name: CI

on:
  - push
  - pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: Lint and Test with Node.js ${{ matrix.node }} on ${{ matrix.os }}
    strategy:
      matrix:
        node:
          - 18
          - 20
          - 22
        os:
          - macos-latest
          - windows-latest
          - ubuntu-latest
      fail-fast: false
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js ${{ matrix.node }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Build
        run: |
          npm run build
          npx napi-postinstall rollup
          npx napi-postinstall unrs-resolver check

      - name: Bad Windows
        if: ${{ matrix.os == 'windows-latest' }}
        run: npm i -D @rollup/rollup-win32-x64-msvc

      - name: Lint and Test
        run: |
          npm run lint
          npm run test
        env:
          PARSER_NO_WATCH: true

      - name: Codecov
        uses: codecov/codecov-action@ad3126e916f78f00edff4ed0317cf185271ccc2d # v5.4.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Run codacy-coverage-reporter
        # bad Windows -- https://github.com/codacy/codacy-coverage-reporter-action/issues/91
        if: ${{ !github.event.pull_request.head.repo.fork && matrix.os != 'windows-latest' }}
        uses: codacy/codacy-coverage-reporter-action@89d6c85cfafaec52c72b6c5e8b2878d33104c699 # v1.3.0
        continue-on-error: true
        with:
          api-token: ${{ secrets.CODACY_API_TOKEN }}
